lugs/urls.py
from django.urls import path
from .views import (LugDeleteView,
                    LugsByUserListView,
                    MyLugsListView,
                    LugsByCityListView,
                    )
from . import views

urlpatterns = [
    path('', views.lugListView, name='lugs-home'),
    path('lugs-by/<str:username>/', LugsByUserListView.as_view(), name='lugs-by-user'),
    path('my-lugs/', MyLugsListView.as_view(), name='my-lugs'),
    path('lug/<str:slug>/', views.lugDetailView, name='lug-detail'),
    path('lug/<str:slug>/delete', LugDeleteView.as_view(), name='lug-delete'),
    path('lugs-in-city/<int:city_id>/', LugsByCityListView.as_view(), name='lugs-by-city'),
    path('find-lugs-in-city/', views.findLugByCityView, name='find-lugs-in-city'),
    path('search-lugs/', views.searchLUGsView, name='search-lugs'),
    path('about/', views.about, name='lugs-about'),
    path('join-lug/<str:slug>/', views.joinLug, name='join-lug'),
    path('leave-lug/<str:slug>/', views.leaveLug, name='leave-lug'),
    path('lug-members/<str:slug>/', views.lugMembersView, name='lug-members'),
    path('create_lug/', views.createLug, name='lug-create'),
    path('edit_lug/<str:slug>/', views.editLug, name='lug-update'),
    path('lug/<str:slug>/create_post', views.createPost, name='create-post'),
    path('lug/edit_post/<int:pk>/', views.editPost, name='edit-post'),
    path('lug/delete_post/<int:pk>/', views.deletePost, name='delete-post'),
    path('lug/<str:slug>/posts', views.lugPostsListView, name='lug-posts'),
    path('lug/post/<int:pk>', views.lugPostDetail, name='post-detail'),
    path('api/lug_list/', views.lug_list, name='api-lug-list'),
    path('api/city_list/', views.city_list, name='api-city-list'),
]

lugs/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.contrib.auth.models import User
from linux_lugs.utils import unique_slug_generator
from django.urls import reverse
from PIL import Image
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from cities_light.models import City



class Lug(models.Model):
    name = models.CharField(verbose_name='LUG Name',
                             help_text='The name you choose for the LUG will be used in the permanent link, you can change the name later but the link will remain unchanged.',
                             max_length=100,
                             null=False,
                             blank=False)
    slug = models.SlugField(max_length=128, null=False, blank=False, default='')
    description = models.TextField(verbose_name='Description', help_text='About LUG, activities, focus, agenda, timing, etc.', null=True, blank=True)
    website = models.URLField(verbose_name='LUG Website', null=True, blank=True, default='')
    cover_image = ProcessedImageField(verbose_name='LUG Cover Image/Logo', default='lug_default_photo.png', upload_to='lug_cover_images',
                                           processors=[ResizeToFill(338, 200)],
                                           format='JPEG',
                                           options={'quality': 80})
    city = models.ForeignKey(City,
                             on_delete=models.CASCADE,
                             help_text='Use up & down arrows, PageUp/Down keys to quickly find your city')
    long = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True, verbose_name='Longitude')
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True, verbose_name='Latitude')

    meetup_place = models.CharField(verbose_name='Meetup Place', help_text='Place where LUG members meet (library, restaurant, coffee shop, etc.)', max_length=250, null=True, blank=True)
    contact_person = models.CharField(verbose_name='Contact Person', max_length=100, null=True, blank=True)
    contact_info = models.CharField(verbose_name='Contact Info', help_text='How to contact LUG organizers (250 characters max).', max_length=250, null=True, blank=True)
    donate_link = models.URLField(verbose_name='Donation Page URL', help_text='Link to page where this LUG accepts donations.', default='', null=True, blank=True)
    youtube_channel = models.URLField(default='', null=True, blank=True)
    twitter = models.URLField(default='', null=True, blank=True)
    facebook = models.URLField(default='', null=True, blank=True)
    telegram = models.URLField(default='', null=True, blank=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('lug-detail', kwargs={'slug': self.slug})


# a pre-save signal to generate a slug and save it
def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Lug)


class Post(models.Model):
    lug = models.ForeignKey(Lug, on_delete=models.CASCADE)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Post Title', max_length=100, null=False, blank=False)
    text = models.TextField(verbose_name='Post Text', null=False, blank=False)
    date_added = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

#TODO
'''
class Membership(models.Model):
    lug = models.ForeignKey(Lug, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_joined = models.DateTimeField(default=timezone.now)
    role = models.SmallIntegerField(
                            choices=[(0, "Normal"), (1, "Moderator"), (2, "Administrator")],
                            verbose_name='Member Role', default=0, null=False, blank=False)
'''

users/models.py
from django.db import models
from django.contrib.auth.models import User
from lugs.models import Lug
from PIL import Image
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from cities_light.models import City

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    real_name = models.CharField(max_length=100, null=True, blank=True, default="")
    image = ProcessedImageField(verbose_name='Profile Photo', default='default.jpeg', upload_to='profile_pics', blank=True,
                                           processors=[ResizeToFill(128, 128)],
                                           format='JPEG',
                                           options={'quality': 80})
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, blank=True)
    lugs = models.ManyToManyField(Lug)
    twitter = models.URLField(default='', null=True, blank=True)
    facebook = models.URLField(default='', null=True, blank=True)
    youtube_channel = models.URLField(default='', null=True, blank=True)


    def __str__(self):
        return self.user.username
    
    # #fix for profile not created issue
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

lugs/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView
                                  )
from .forms import LugForm,PostForm, FindLugByCityForm
from .models import Lug, Post
from users.models import Profile
from cities_light.models import City

# serializer imports
from django.http import Http404, HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from lugs.serializers import LugSerializer, CitySerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response


def lugListView(request):
    lugs = Lug.objects.all().order_by('-date_added')
    latest_lugs = lugs[:5]

    context = {'lugs': lugs, 'latest_lugs': latest_lugs}
    return render(request, 'lugs/home.html', context)


class LugsByUserListView(ListView):
    model = Lug
    template_name = 'lugs/lugs_by_user.html'
    context_object_name = 'lugs'
    paginate_by = 25

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Lug.objects.filter(added_by=user).order_by('-date_added')


def lugDetailView(request, slug):
    lug = get_object_or_404(Lug, slug=slug)
    similar_lugs = Lug.objects.filter(city=lug.city)[:3]

    context = {
            'lug': lug,
            'title': f'About LUG: {lug.name}',
            'similar_lugs': similar_lugs,
            }
    return render(request, 'lugs/lug_detail.html', context)


def searchLUGsView(request):
    lugs = ''
    query = request.GET.get('q')
    if query:
        lugs = Lug.objects.filter(name__icontains=query)
        
        if not lugs:
            messages.warning(request, f'Your search \"{query}\" returned no results.')
    context = {
        'lugs': lugs,
        'query': query,
        'title': 'search LUGs'
        }
    return render(request, 'lugs/search_lugs.html', context)

@login_required
def createLug(request):
    user = request.user

    if request.method == 'POST':
        form = LugForm(request.POST, request.FILES)
        if form.is_valid():
            new_lug = form.save(commit=False)
            creator = User.objects.filter(username=user.username).first()
            new_lug.added_by = creator
            new_lug.save()
            creator.profile.lugs.add(new_lug)
            form = LugForm()
            messages.success(request, f'Your new LUG has been successfully created.')
            return redirect('lug-detail', slug=new_lug.slug)
        else:
            form = LugForm(request.POST)
    
    form = LugForm()
    context = {
        'form': form,
        'title': 'Add a new Linux LUG' 
        }
    return render(request, 'lugs/create_lug.html', context)


@login_required
def editLug(request, slug):
    lug = get_object_or_404(Lug, slug=slug)
    user = request.user

    if lug.added_by == user:
        if request.method == 'POST':
            form = LugForm(request.POST, request.FILES, instance=lug)
            if form.is_valid():
                form.save()
                messages.success(request, f'Your changes have been saved.')
                return redirect('lug-detail', slug=lug.slug)
            else:
                form = LugForm(request.POST)
    
        form = LugForm(instance=lug)
        context = {
            'form': form,
            'lug': lug,
            'title': f'Update LUG: {lug.name}'
            }
        return render(request, 'lugs/edit_lug.html', context)
    else:
        messages.warning(request, f'You can edit only LUGs you have created')
        return redirect('lug-detail', slug=lug.slug)


class LugDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Lug
    success_url = '/'

    def test_func(self):
        lug = self.get_object()
        if self.request.user == lug.added_by:
            return True
        return False


class MyLugsListView(LoginRequiredMixin, ListView): 
    model = Lug
    template_name = 'lugs/my_lugs.html'
    context_object_name = 'lugs'
    paginate_by = 25

    def get_queryset(self):
        current_user = self.request.user
        return Lug.objects.filter(added_by=current_user).order_by('-date_added')


class LugsByCityListView(ListView): #use try/except
    model = Lug
    template_name = 'lugs/lugs_by_city.html'
    context_object_name = 'lugs'
    paginate_by = 25

    def get_queryset(self):
        city_id = self.kwargs.get('city_id')
        lugs = Lug.objects.filter(city_id=city_id).order_by('-date_added')
        return lugs


@login_required
def joinLug(request, slug):
    profile = request.user.profile
    lug = get_object_or_404(Lug, slug=slug)
 
    if request.method == 'POST':
        if profile not in lug.profile_set.all():
            profile.lugs.add(lug)
            messages.success(request, f'Your are now a member of this LUG')            
            return redirect('lug-detail', slug=slug)
        else:
            messages.warning(request, f'Your are already a member of this LUG!')
            return redirect('lug-detail', slug=slug)

    return render(request, 'lugs/join_lug.html', {'slug': slug, 'title': f'Join LUG {lug.name}' })


@login_required
def leaveLug(request, slug):
    user = request.user
    profile = user.profile
    lug = get_object_or_404(Lug, slug=slug)

    if request.method == 'POST':
        if profile in lug.profile_set.all():
            if lug.added_by == user:
                messages.warning(request, f'You can NOT leave LUGs you created!')            
                return redirect('lug-detail', slug=slug)
            profile.lugs.remove(lug)
            messages.success(request, f'Your have successfully left this LUG')            
            return redirect('lug-detail', slug=slug)
        else:
            messages.warning(request, f'Your are not a member of this LUG!')
            return redirect('lug-detail', slug=slug)

    return render(request, 'lugs/leave_lug.html', {'slug': slug, 'title': f'Leave LUG {lug.name}'})


def lugMembersView(request, slug):
    lug = get_object_or_404(Lug, slug=slug)
    members = lug.profile_set.all()
    context = {'lug': lug, 'members': members, 'title': f'Members of LUG {lug.name}'}

    return render(request, 'lugs/lug_members_list.html', context)


def findLugByCityView(request):
    title = 'Find Nearby LUGs'
    form = FindLugByCityForm()
    query = request.GET.get('city')
    if query:
        lugs = Lug.objects.filter(city=query)
        form = FindLugByCityForm(request.GET)
        context = {'title': title, 'lugs': lugs, 'form': form}
        if not lugs:
            messages.warning(request, f'No LUGs found in this city.')
        return render(request, 'lugs/find_lugs_in_city.html', context)

    context = {
        'form': form,
        'title': title 
        }
    return render(request, 'lugs/find_lugs_in_city.html', context)

'''
        LUG POSTS
'''
def lugPostsListView(request, slug):
    lug = get_object_or_404(Lug, slug=slug)
    posts = Post.objects.filter(lug=lug).order_by('-date_added')
    context = {'lug': lug, 'posts': posts}
    return render(request, 'lugs/lug_posts.html', context)

def lugPostDetail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    
    return render(request, 'lugs/post_detail.html', {'post': post, 'title': f'Post Detail {post.title}'})

@login_required
def createPost(request, slug):
    lug = get_object_or_404(Lug, slug=slug)
    user = request.user

    if lug.added_by == user:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                new_post = form.save(commit=False)
                new_post.lug = lug
                poster = User.objects.filter(username=user.username).first()
                new_post.posted_by = poster
                form.save()
                messages.success(request, f'Your post has been created')
                return redirect('lug-detail', slug=lug.slug)
            else:
                form = PostForm(request.POST)
    
        form = PostForm()
        return render(request, 'lugs/post_create.html', {'form': form, 'lug': lug, 'title': f'Create a Post for LUG {lug.name}'})
    else:
        messages.warning(request, f'You are not allowed to post to this LUG')
        return redirect('lug-detail', slug=lug.slug)

@login_required
def editPost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user

    if post.posted_by == user:
        if request.method == 'POST':
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                form.save()
                messages.success(request, f'Post updated.')
                return redirect('post-detail', pk=pk)
            else:
                form = PostForm(request.POST)
    
        form = PostForm(instance=post)
        return render(request, 'lugs/post_edit.html', {'form': form, 'post': post, 'title': f'Update Post {post.title}'})
    else:
        messages.warning(request, f'You can edit only LUGs you have created')
        return redirect('lug-posts', slug=post.lug.slug)

def deletePost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user

    if post.posted_by == user or post.lug.added_by == user:
        if request.method == 'POST':
            post.delete()
            messages.success(request, f'Post deleted!')
            return redirect('lug-posts', slug=post.lug.slug)

        return render(request, 'lugs/post_delete.html', {'post': post, 'title': f'Delete Post {post.title}'})
    else:

lugs/templates/lugs/create_lug.html
{% extends "lugs/base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<h1></h1>
    <div class="content-sections">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class ="form-group">
                <legend class="border-bottom mb-4">Add a new LUG</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

lugs/templates/lugs/find_lugs_in_city.html
{% extends "lugs/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<!-- start find LUGs by city form -->
<div class="row">
        <div class="col-md-12">
            <form class="form-control" action="{% url 'find-lugs-in-city' %}" method="GET">
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Find LUGs in Your City</legend>
                        {{form|crispy}}
                        <input class="btn btn-primary" type="submit" value="Find Nearby LUGs">
                    </fieldset>
            </form>
    </div>
</div>
<!-- end search box-->


<div class="row">
{% if lugs %}
<h3 class="mb-3">Found ({{ lugs.count }}) LUG(s) in <strong>{{ lugs.first.city }}</strong></h3>
                   
{% for lug in lugs %}

<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-banner">
            <a href="{% url 'lug-detail' lug.slug %}">
                <img class="card-img-top"
                    src="{{ lug.cover_image.url }}"
                    alt="{{ lug.name }} cover image">
            </a>
            <p class="card-title"><strong>{{ lug.name }}</strong></p>
        </div>
        <div class="card-body">
                <p class="card-text text-muted"><i class="fa fa-map-marker text-muted mr-2" aria-hidden="true"></i>{{ lug.city|truncatewords:4 }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">
                        <i class="fa fa-users mr-1" aria-hidden="true"></i>{{lug.profile_set.all.count}}
                        <i class="fa fa-user ml-2" aria-hidden="true"></i> <a href="{% url 'public-profile' lug.added_by.username %}">{{ lug.added_by|slice:":20" }} </a>
                    </small>
                    <div class="btn-group">
                        <a class="btn btn-outline-info" href="{% url 'lug-detail' lug.slug %}">View</a>
                    </div>
                </div>
        </div>
    </div>
</div>

{% endfor %}


{% endif %}

</div>

{% include "lugs/pagination.html" %}

{% endblock content %}

lugs/templates/lugs/leave_lug.html
{% extends "lugs/base.html" %}
{% block content %}
<div class="content-sections">
    <form method="POST">
        {% csrf_token %}
        <fieldset class ="form-group">
            <legend class="border-bottom mb-4">Are sure you want to leave this Linux User Group?</legend>

        </fieldset>
        <div class="form-group">
            <button class="btn btn-danger" type="submit">Yes, Leave!</button>
            <a class="btn btn-secondary" href="{% url 'lug-detail' slug %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

lugs/templates/lugs/lug_detail.html
{% extends "lugs/base.html" %}

{% block content %}
<lug class="media content-section">

    <div class="media-body">
        <div class="lug-metadata">
            <h1 class="lug-title">{{ lug.name }}</h1>
            <img class="mb-3" src="{{ lug.cover_image.url }}" alt="cover image for {{lug.name}}">
        </div>
        <p class="lug-content"><strong>About this LUG: </strong>
            {{ lug.description }}</p>
     </div>
</lug>


<!-- start LUG posts  -->
<a name="lug-posts"></a>

<h3><i class="fa fa-bullhorn fa-lg text-muted" aria-hidden="true"></i> LUG Updates & Announcements ({{lug.post_set.count}})</h3>
<br><p><a class="btn btn-outline-info" href="{% url 'lug-posts' lug.slug %}">See All</a></p>

{% if lug.post_set %}
    {% for post in lug.post_set.all %}
        <div class="post-section">
                    <h5 class="post-title"><img class="lug-thumb rounded-circle mr-2 mb-2" src="{{ post.posted_by.profile.image.url }}">{{ post.title }}</h5>
                    <small>Posted by: <a class="mr-2" href="{% url 'public-profile' post.posted_by.username %}">{{ post.posted_by }}</a> On: {{ post.date_added }}</small>
                <p class="post-content">
                    {{ post.text|truncatewords:30 }}</p>
                <a class="btn btn-outline-info btn-sm" href="{% url 'post-detail' post.pk %}">Read More...</a>
        </div>
    {% endfor %}
{% else %}
    <p>No posts for this LUG yet.</p>
{% endif %}
{% if user.profile in lug.profile_set.all and lug.added_by == user %}
    <p>
    <a class="btn btn-success" href="{% url 'create-post' lug.slug %}">Create a Post</a>
    </p>

{% endif %}
<!-- End LUG posts -->

<!-- LUGs in same city as currnt LUG -->
<h3 class="border-top mb-3 mt-3">Other LUGs in <b>{{ lug.city }}</b> :</h3>
<div class="col-md-6">

{% for sim_lug in similar_lugs %}
    {% if sim_lug != lug %}
    <div>
        <p><a href="{% url 'lug-detail' sim_lug.slug %}">
            <img class="lug-thumb rounded-circle mr-1" src="{{ sim_lug.cover_image.url }}"><b>{{sim_lug.name }}</b></a>
            <!-- <small><i class="fa fa-users mr-1 text-muted" aria-hidden="true"></i>{{lug.profile_set.all.count}}</small> -->
        </p>
        
    </div>
    {% endif%}
{% endfor %}
</div>
<!-- end similar LUGs-->


{% endblock content %}

{% block sidebar %}
<!-- start side bar--> 
<div class="col-md-4">
        <div class="content-section">
                {% if user.profile in lug.profile_set.all and lug.added_by == user %}
                    <div class="border-bottom">
                        <p>You are the creator of this LUG 
                        <br><a class="btn btn-success" href="{% url 'lug-update' lug.slug %}">Edit LUG</a>
                        </p>
                    </div>
                {% endif %}
                <!-- Join/Leave LUG button -->
                {% if user.profile in lug.profile_set.all and lug.added_by != user %}
                    <div class="border-bottom">
                        <p>You're currently a member of this LUG 
                        <br><a class="btn btn-danger" href="{% url 'leave-lug' lug.slug %}">Leave LUG</a>
                        </p>
                    </div>
                {% endif %}    
                {% if user.profile not in lug.profile_set.all %}
                    <div class="border-bottom">
                        <p><a class="btn btn-success" href="{% url 'join-lug' lug.slug %}">Join LUG</a></p>
                    </div>
                {% endif %}
                <!-- End Join/Leave LUG button-->
                <div class="mt-3">
                    <a class="btn btn-outline-info mb-2" href="#lug-posts">News & Updates</a>
                    <p><i class="fa fa-map-marker fa-lg text-muted" aria-hidden="true"></i> City: 
                        <a href="{% url 'lugs-by-city' lug.city_id %}">{{ lug.city }}</a></p>
                    <p><i class="fa fa-users fa-lg text-muted" aria-hidden="true"></i> {{ lug.profile_set.all.count }} member(s)</p>
                    <p><i class="fa fa-user fa-lg text-muted" aria-hidden="true"></i> Added by: <a class="mr-2" href="{% url 'public-profile' lug.added_by.username %}">{{ lug.added_by }}</a></p>
                    <p><i class="fa fa-calendar-plus-o fa-lg text-muted" aria-hidden="true"></i> Added On: {{ lug.date_added|date:"d, n, Y" }}</p>
                    <p><i class="fa fa-refresh fa-lg text-muted" aria-hidden="true"></i> Last Updated:  {{ lug.last_updated|date:"d, n, Y" }}</p>
                    <hr>
                    <p><i class="fa fa-link fa-lg text-muted" aria-hidden="true"></i> Links: </p>
                    <p>
                        <a href="{{ lug.website }}" target="_blank"><i class="fa fa-home fa-2x text-muted" aria-hidden="true"></i></a>
                        <a href="{{ lug.youtube_channel }}" target="_blank"><i class="fa fa-youtube fa-2x text-muted" aria-hidden="true"></i></a>
                        <a href="{{ lug.twitter }}" target="_blank"><i class="fa fa-twitter fa-2x text-muted" aria-hidden="true"></i></a>                        
                        <a href="{{ lug.facebook }}" target="_blank"><i class="fa fa-facebook fa-2x text-muted" aria-hidden="true"></i></a>                        
                        <a href="{{ lug.telegram }}" target="_blank"><i class="fa fa-telegram fa-2x text-muted" aria-hidden="true"></i></a>
                    </p>
                    <hr>
                    <p><i class="fa fa-map-pin fa-lg text-muted" aria-hidden="true"></i> Meetup Place: {{ lug.meetup_place }}</p>
                    <p><i class="fa fa-address-book fa-lg text-muted" aria-hidden="true"></i> Contact Person: {{ lug.contact_person }}</p>
                    <p><i class="fa fa-address-card fa-lg text-muted" aria-hidden="true"></i> Contact Info: {{ lug.contact_info }}</p>
                    <p><i class="fa fa-support fa-lg text-muted" aria-hidden="true"></i> <a href="{{ lug.donate_link }}" target="_blank">Support this LUG</a></p>
                </div>
            </div>
            <div class="content-section">
                <div class="mb-2 mt-2">
                    <p><i class="fa fa-users fa-lg text-muted" aria-hidden="true"></i><strong> Members  ({{lug.profile_set.all.count}})</strong></p>
                    <div>
                    {% for profile in lug.profile_set.all %}
                        <p>
                            <small class="text-muted"><a href="{% url 'public-profile' profile %}">
                            <img class="lug-thumb rounded-circle mr-1" src="{{ profile.image.url }}">{{ profile }}</a></small>
                        </p>
                    {% endfor %}
                    </div>
                    <br>
                    <a class="btn btn-outline-info" href="{% url 'lug-members' lug.slug %}">All Members</a>
                </div>
            </div>
        </div>
        <!-- end side bar-->
{%  endblock sidebar %}

lugs/templates/lugs/lug_form.html
{% extends "lugs/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-sections">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class ="form-group">
                <legend class="border-bottom mb-4">Create/Update LUG</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">Save</button>
                <!-- neccessary for new lug form to work with a delete button-->
                {% if lug.slug %}
                <a class="btn btn-secondary" href="{% url 'lug-detail' lug.slug %}">Cancel</a>
                <a class="btn btn-danger" href="{% url 'lug-delete' lug.slug %}">Delete LUG</a>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock content %}

lugs/templates/lugs/pagination.html
{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">&laquo;First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last&raquo;</a>
    {% endif %}

{% endif %}